SRC 		:= linked_list/singly_linked_list.c linked_list/doubly_linked_list.c linked_list/circular_linked_list.c tree/binary_search_tree.c queue.c stack.c main.c
EXECUTABLE	:= ../bin/data_structures

all: $(EXECUTABLE)

$(EXECUTABLE):
	$(CC) $(SRC) -o $(EXECUTABLE)
